#!/bin/bash

pdbf=('4M0_ed') # '6M90_ed')

npatterns=100 ## 5=1.5h, 100=?1.3d or 1000 =?12d ##
noise=(None 'poisson') ## i = 2, 2 cases ##
name=('Fnoise_BeamNarrInt' 'Pnoise_BeamNarrInt')
#name=('test_Pnoise' 'test_noisefree') # [0]= Pois, [1]=None 

## location of run file: /home/cldah/source/XCCA-simulations/CsCl :##
CURRDIR=`pwd` 
LOGGDIR="$CURRDIR/Loggs"
## Store large CXI-files in scratch-folder (OBS! ): ##
STOREDIR="/home/cldah/cldah-scratch/condor_cxi_files"
#LINKNAME="store_on_scratch"

if test ! -e $LOGGDIR; then
	mkdir $LOGGDIR
	echo "Created "$LOGGDIR
fi
if test ! -e $STOREDIR; then
	mkdir $STOREDIR
	echo "Created "$STOREDIR
fi

#fi
for conc in "${pdbf[@]}"; do
	#for ns in "${noise[@]}"; do
	#for (( i=0; i<=1; i++)); do  ##  ${#a[@]} ##
	for (( i=0; i<=${#name[@]}; i++)); do  ##  or ${#noise[@]} == ${#name[@]} length should be eq ##
		echo "Running Simulations of $conc with ${noise[i]}-noise..."
		echo '#!/bin/bash'> $LOGGDIR/CsCl_simulate.sh
		echo '' >> $LOGGDIR/CsCl_simulate.sh
		echo '#SBATCH -o '$LOGGDIR/'CsCl_simulate_'"${pdbf[i]}"'_'"${noise[i]}"'.out' >> $LOGGDIR/CsCl_simulate.sh
		#echo '#SBATCH -o '"$LOGGDIR/"'CsCl_simulate_'"${pdbf[i]}"'_'"${noise[i]}"'.out' >> $LOGGDIR/CsCl_simulate.sh
		echo '#SBATCH -e $'LOGGDIR/'CsCl_simulate_'"${pdbf[i]}"'_'"${noise[i]}"'.err' >> $LOGGDIR/CsCl_simulate.sh
		echo '' >> $LOGGDIR/CsCl_simulate.sh
		echo '#SBACH --gres=gpu:2' >> $LOGGDIR/CsCl_simulate.sh  ## Request 2 GPUs per node for CUDA##
		
		echo 'module load cuda' >> $LOGGDIR/CsCl_simulate.sh
		echo 'HOST=`hostname`' >> $LOGGDIR/CsCl_simulate.sh
		echo 'echo "Node: $HOST" ' >> $LOGGDIR/CsCl_simulate.sh
		#if [ $i -eq 1 ]; then  ## [1]=None
		if [ $i -eq 0 ]; then 
			echo '/davinci/Cellar/Python/miniconda3/envs/py2/bin/python test_CsCl_84-X_v6.py' '-f' "${name[i]}" '-n' "$npatterns" '-pdb' "$conc" '-o' "$STOREDIR" >> $LOGGDIR/CsCl_simulate.sh
		else	
			echo '/davinci/Cellar/Python/miniconda3/envs/py2/bin/python test_CsCl_84-X_v6.py -dn' "${noise[i]}" '-f' "${name[i]}" '-n' "$npatterns" '-pdb' "$conc" '-o' "$STOREDIR" >> $LOGGDIR/CsCl_simulate.sh
		fi
		#module load CUDA

		sbatch -p regular $LOGGDIR/CsCl_simulate.sh  ## regular max  2days ##
		##sbatch -p scavenger $LOGGDIR/CsCl_simulate.sh ## regular max  30days ##
		##local term dep## srun /davinci/Cellar/Python/miniconda3/envs/py2/bin/python test_CsCl_84-X_v6.py -dn "${noise[i]}" -f "${name[i]}" -n "$npatterns" -pdb "$conc"
	done
done
squeue -u cldah
